// Sample hotel data
 export const hotels= [
  {
    id: "1",
    name: "Bogmallo Beach Resort",
    location: "Bogmalo, Goa",
    area: "South Goa",
    stars: 5,
    originalPrice: 16000,
    discountedPrice: 13078,
    amenities: ["Free WiFi", "Swimming pool", "Jacuzzi"],
    viewers: 0,
    tags: ["WOMEN FRIENDLY", "COUPLE FRIENDLY", "ECO+"],
    savings: 2922,
    featured: true,
    rating: {
      score: 4.1,
      type: "Excellent",
      reviews: 12928,
    },
    image: "/assets/Swimming_Pool.webp",
  },
  {
    id: "2",
    name: "Bambolim Beach Resort",
    location: "Bambolim, Goa",
    area: "North Goa",
    stars: 4,
    originalPrice: 18000,
    discountedPrice: 8853,
    amenities: ["Free Breakfast", "Free WiFi", "Swimming pool", "Private beach"],
    viewers: 4,
    tags: ["WOMEN FRIENDLY", "ECO+"],
    savings: 9147,
    featured: true,
    rating: {
      score: 4.0,
      type: "Very Good",
      reviews: 3731,
    },
    image: "/assets/bambolimBeach.jpg",
  },
  {
    id: "3",
    name: "Paradise Village Beach Resort",
    location: "Calangute, Goa",
    area: "North Goa",
    stars: 3,
    originalPrice: 7000,
    discountedPrice: 5497,
    amenities: ["Swimming pool"],
    viewers: 0,
    tags: ["COUPLE FRIENDLY"],
    savings: 1503,
    featured: true,
    rating: {
      score: 3.8,
      type: "Very Good",
      reviews: 4163,
    },
    image: "/assets/paradiseVillage.jpg",
  },
  {
    id: "4",
    name: "Marquis Beach Resort",
    location: "Candolim, Goa",
    area: "North Goa",
    stars: 4,
    originalPrice: 14500,
    discountedPrice: 14500,
    amenities: ["Free Breakfast", "Free WiFi", "Swimming pool", "Bar"],
    viewers: 0,
    tags: ["WOMEN FRIENDLY", "COUPLE FRIENDLY", "ECO+"],
    savings: 0,
    featured: true,
    rating: {
      score: 4.3,
      type: "Excellent",
      reviews: 6156,
    },
    image: "/assets/marquiss.jpg",
  },
  {
    id: "5",
    name: "Cuba Patnem",
    location: "Canacona, Goa",
    area: "South Goa",
    stars: 3,
    originalPrice: 7000,
    discountedPrice: 3591,
    amenities: ["Free Breakfast", "Bar"],
    viewers: 0,
    tags: [],
    savings: 3409,
    featured: true,
    rating: {
      score: 4.3,
      type: "Excellent",
      reviews: 667,
    },
    image: "/assets/cubapatnem.avif",
  },
  {
    id: "6",
    name: "Casablanca",
    location: "Candolim, Goa",
    area: "North Goa",
    stars: 3,
    originalPrice: 12000,
    discountedPrice: 5578,
    amenities: ["Swimming pool", "Bar"],
    viewers: 1,
    tags: ["COUPLE FRIENDLY"],
    savings: 6422,
    featured: true,
    rating: {
      score: 3.9,
      type: "Very Good",
      reviews: 1660,
    },
    image: "/assets/casablanca.avif",
    bookings: {
      times: 2,
      hours: 24,
    },
  },
  {
    id: "7",
    name: "Resorte Marinha Dourada",
    location: "Baga, Goa",
    area: "North Goa",
    stars: 3,
    originalPrice: 6400,
    discountedPrice: 5291,
    amenities: ["Free Breakfast", "Swimming pool", "Health club", "Bar"],
    viewers: 1,
    tags: ["WOMEN FRIENDLY", "COUPLE FRIENDLY"],
    savings: 1109,
    featured: true,
    rating: {
      score: 4.0,
      type: "Very Good",
      reviews: 2794,
    },
    image: "/assets/resortemarinha.avif",
  },
  {
    id: "8",
    name: "Soul Vacation Resort and Spa",
    location: "Colva, Goa",
    area: "South Goa",
    stars: 4,
    originalPrice: 27998,
    discountedPrice: 22884,
    amenities: ["Free WiFi", "Swimming pool", "Bar"],
    viewers: 0,
    tags: ["WOMEN FRIENDLY", "COUPLE FRIENDLY"],
    savings: 5114,
    featured: true,
    rating: {
      score: 4.2,
      type: "Excellent",
      reviews: 1455,
    },
    image: "/assets/soulvacationresportspa.avif",
  },
]
